#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : abireport
Version  : 1.0.5
Release  : 7
URL      : https://github.com/clearlinux/abireport/releases/download/v1.0.5/abireport-1.0.5.tar.gz
Source0  : https://github.com/clearlinux/abireport/releases/download/v1.0.5/abireport-1.0.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: abireport-bin
Requires: abireport-doc
BuildRequires : go

%description
abireport
----------
[![Report](https://goreportcard.com/badge/github.com/clearlinux/abireport)](https://goreportcard.com/report/github.com/clearlinux/abireport) [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)

%package bin
Summary: bin components for the abireport package.
Group: Binaries

%description bin
bin components for the abireport package.


%package doc
Summary: doc components for the abireport package.
Group: Documentation

%description doc
doc components for the abireport package.


%prep
%setup -q -n abireport-1.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518587959
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1518587959
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/abireport

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
